# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 workspace './soqqle.xcworkspace'
 install! 'cocoapods', :deterministic_uuids => false

 target 'RNSVG' do
   project '../node_modules/react-native-svg/ios/RNSVG.xcodeproj'
 end

 target 'RNMixpanel' do
   project '../node_modules/react-native-mixpanel/RNMixpanel.xcodeproj'
 end

 target 'RNViewShot' do
   project '../node_modules/react-native-view-shot/ios/RNViewShot.xcodeproj'
 end

target 'soqqle' do
  pod 'Firebase/Core', '~> 6.3.0'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Messaging', '~> 6.3.0'
  # pod 'Fabric', '~> 1.9.0'
  # pod 'Crashlytics', '~> 3.12.0'
  # pod 'AppCenter/Crashes', '~> 1.14.0'
  # pod 'AppCenter/Analytics', '~> 1.14.0'
  # pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Mixpanel'
  # Pods for soqqle
    rn_maps_path = '../node_modules/react-native-maps'
      inherit! :search_paths
    # Pods for AwesomeProject

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'Bolts'
  pod 'FBSDKCoreKit', '4.40.0'
  pod 'FBSDKLoginKit', '4.40.0'
  pod 'FBSDKShareKit', '4.40.0'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes/ios'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  
  #pod 'AppCenter/Core', '> 2.3.0'
  #pod 'AppCenter/Analytics', '> 2.3.0'
  #pod 'AppCenterReactNativeShared', '> 2.3.0'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'IQAudioRecorderController', :git => 'https://github.com/prscX/IQAudioRecorderController', :branch => 'wav'

  # use_native_modules!

  pod 'RNVoiceRecorder', :path => '../node_modules/react-native-voice-recorder/ios'
end